name: sem6000_app
description: BLE power logger for Voltcraft SEM6000
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.12
  path_provider: ^2.1.1
  csv: ^6.0.0
  permission_handler: ^11.3.0
  share_plus: ^11.0.0
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
